#!/usr/bin/env python

from optparse import OptionParser
import string, sys

p = OptionParser()
p.add_option('--prop', default='')
opt, args = p.parse_args()

moduleName = string.join(args, '.')

zope = __import__(moduleName)

o = zope
args = args[1:]

for x in args:
    try:
        o = getattr(o, x)
    except:
        print sys.exc_info()
        dir(o)

help(getattr(o, opt.prop)) if opt.prop else help(o)
'''
if not opt.prop:
    help(o)
else:
    help(getattr(o, opt.prop))
'''
